Move ms-package to 'dependencies'
Move ms-package from 'devDependencies' to 'dependencies'. Couse you always use it.

Otherwise I get:

Error: Cannot find module 'ms'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/zag2art/work/derbygen/node_modules/serve-favicon/index.js:16:10)
  at Module._compile (module.js:456:26)